### ISSUE TITLE
remove use of File::Share::ProjectDistDir

### ISSUE THREAD

**Issue by karenetheridge** [perl-pod/Pod-Spell#19]
File::ShareDir is a much cleaner solution.

I'm willing to do the patch or whatever less/more else is necessary. If you want to hand off comaint that's fine too (and also totally fine if you don't).

**Comment by xenoterracide** [comment]
I can't give you comaint, I'm not the primary maintainer on pause, you're welcome to ask him for it.

**Comment by karenetheridge** [comment]
@xeno This issue is no longer visible on the website; can you re-enable
github issues for this repository please?

**Comment by xenoterracide** [comment]
why?

On Sat, May 9, 2015 at 6:43 PM, Karen Etheridge <notifications@github.com>
wrote:

> @xeno This issue is no longer visible on the website; can you re-enable
> github issues for this repository please?
>
> On Fri, Apr 24, 2015 at 12:28 PM, Caleb Cushing <notifications@github.com>
> wrote:
>
> > I can't give you comaint, I'm not the primary maintainer on pause, you're
> > welcome to ask him for it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/xenoterracide/Pod-Spell/issues/19#issuecomment-96042196
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xenoterracide/Pod-Spell/issues/19#issuecomment-100562651>
> .
>



-- 
Caleb Cushing

http://xenoterracide.com

Calendar:
https://www.google.com/calendar/embed?src=xenoterracide%40gmail.com&ctz=America/Chicago

**Comment by karenetheridge** [comment]
I'm concerned about the loss of continuity by losing the history of
previous issues.

**Comment by dolmen** [comment]
Fixed with #26 which has been released with Pod-Spell 1.20.
