### ISSUE TITLE
stopword stripping behaviour has changed

### ISSUE THREAD

**Issue by tonycoz** [perl-pod/Pod-Spell#21]
This might not be considered a bug, but it comes down to:
```
$ perl -MPod::Wordlist -le '$w = Pod::Wordlist->new(); $w->learn_stopwords("anaglyph"); print $w->strip_stopwords("anaglyph.pl")'
 anaglyph.pl.
```
Imager includes pod (samples/anaglyph.pl) like the following, which passed a spell check with Pod::Spell 1.01:

```
=head1 NAME

=for stopwords anaglyph anaglyph.pl

anaglyph.pl - create a anaglyph from the source images
```

but 1.15 and 1.17 converts the plain text to:

```
anaglyph.pl - create a from the source images
```

which the spell checker (aspell in my case) rejects.

If this is intentional behaviour I'll leave my workaround in place.

**Comment by karenetheridge** [comment]
This sounds like a strange regression.  Is anyone up for a bisect run?
