### ISSUE TITLE
Setup CI with GitHub Actions

### ISSUE THREAD

**Issue by dolmen** [perl-pod/Pod-Spell#32]
A setup of GitHub Actions to test the codebase against multiple versions of Perl would be helpful.

But, despites I'm a maintainer of this project (@dolmen), I'm quite away from the Perl world, so help would be helpful.

That is required to give me confidence for a merge of #31.

Cc: @haarg @karenetheridge

**Comment by haarg** [comment]
I've added GitHub Actions testing.
